version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: user-login-postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user_login_db
    ports:
      - '5433:5432'
    networks:
      - postgres-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local 